mode: Mainline

# Enable conventional commit messages for version bumping
major-version-bump-message: '^(feat!|.*BREAKING CHANGE:.*)'
minor-version-bump-message: '^feat(\(.+\))?:'
patch-version-bump-message: '^fix(\(.+\))?:'

branches:
  main:
    regex: ^main$
    is-release-branch: true
    is-mainline: true

  dev:
    regex: ^dev$
    mode: ContinuousDeployment
    tag: preview
    increment: inherit
    is-mainline: false
    source-branches:
      - main

ignore:
  sha: []