mode: Mainline

# Enable conventional commit messages for version bumping
major-version-bump-message: '^(feat!|.*BREAKING CHANGE:.*)'
minor-version-bump-message: '^feat(\(.+\))?:'
patch-version-bump-message: '^fix(\(.+\))?:'

branches:
  main: {}

ignore:
  sha: []

merge-message-formats: {}
