mode: Mainline

# Enable conventional commit messages for version bumping
major-version-bump-message: '^(feat!|.*BREAKING CHANGE:.*)'
minor-version-bump-message: '^feat(\(.+\))?:'
patch-version-bump-message: '^fix(\(.+\))?:'

branches:

  main:
    is-release-branch: true
    is-mainline: true

  dev:
    mode: ContinuousDeployment
    tag: preview
    increment: inherit

ignore:
  sha: []

