mode: Mainline

# Enable conventional commit messages for version bumping
major-version-bump-message: '(?i)(feat!|.*breaking change:.*)'
minor-version-bump-message: '(?i)\bfeat(\s*\(.+\))?:'
patch-version-bump-message: '(?i)\bfix(\s*\(.+\))?:'

branches:
  main:
    regex: ^main$
    is-release-branch: true
    is-mainline: true

  dev:
    regex: ^dev$
    mode: ContinuousDeployment
    tag: preview
    increment: inherit
    is-mainline: false
    source-branches:
      - main

ignore:
  sha: []